#!/bin/bash
# F1 LakeHouse - Quick Commands Reference
# Use the virtual environment that's already configured

VENV="/Volumes/SAMSUNG/apps/f1-dash/.venv/bin/python"
PROJECT="/Volumes/SAMSUNG/apps/f1-dash"

cd "$PROJECT"

echo "════════════════════════════════════════════════════════════════"
echo "F1 LAKEHOUSE - QUICK COMMANDS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. EXPORT 2024 SEASON (with automatic sprint handling)"
echo "   Command:"
echo "   $VENV scripts/fastf1_export_season.py --year 2024 --auto-format"
echo ""
echo "2. EXPORT 2023 SEASON"
echo "   Command:"
echo "   $VENV scripts/fastf1_export_season.py --year 2023 --auto-format"
echo ""
echo "3. PREVIEW EXPORT (dry-run, doesn't write files)"
echo "   Command:"
echo "   $VENV scripts/fastf1_export_season.py --year 2024 --auto-format --dry-run"
echo ""
echo "4. BUILD PREDICTIONS TABLE"
echo "   Command:"
echo "   $VENV scripts/build_predictions_table.py"
echo ""
echo "5. RUN EXPORT GUIDE"
echo "   Command:"
echo "   $VENV scripts/FASTF1_EXPORT_GUIDE.py"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "SHORT VERSION - Just copy and paste these in your terminal:"
echo ""
echo "# Test export (no file writes)"
echo "/Volumes/SAMSUNG/apps/f1-dash/.venv/bin/python /Volumes/SAMSUNG/apps/f1-dash/scripts/fastf1_export_season.py --year 2024 --auto-format --dry-run"
echo ""
echo "# Real export (writes to bronze_fastf1)"
echo "/Volumes/SAMSUNG/apps/f1-dash/.venv/bin/python /Volumes/SAMSUNG/apps/f1-dash/scripts/fastf1_export_season.py --year 2024 --auto-format"
echo ""
echo "# Rebuild predictions"
echo "/Volumes/SAMSUNG/apps/f1-dash/.venv/bin/python /Volumes/SAMSUNG/apps/f1-dash/scripts/build_predictions_table.py"
echo ""
echo "════════════════════════════════════════════════════════════════"
